# GBDB CarbEnMats // Benchmarking

Author: Martin RÃ¶ck (www.martinroeck.com)

In [117]:
script_title = 'GBDB CarbEnMats // Benchmarking'

In [118]:
print('Running: ' + script_title)

Running: GBDB CarbEnMats // Benchmarking

# Setup

## Modules

In [119]:
# SETUP
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time

In [120]:
# Ignore warnings
import warnings
warnings.filterwarnings('ignore') #gets rid of the 'red' warnings

## Data loading

In [121]:
# File(s)
filepath = ''
filename = 'gbdb_data'

In [122]:
%%time
# Read CSV
#df = pd.read_csv(filepath + filename +'.csv')

CPU times: total: 0 ns
Wall time: 0 ns

In [123]:
%%time
# Read XLS
#df = pd.read_excel(filepath + filename +'.xlsx')

CPU times: total: 0 ns
Wall time: 0 ns

In [124]:
# Load the data from the specified sheet into a DataFrame
#sheet_name = "CORE"
sheet_name = "FULL"

df = pd.read_excel(filepath + filename +'.xlsx', sheet_name=sheet_name)

## General Information

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1294 entries, 0 to 1293
Columns: 335 entries, Unnamed: 0 to GHG_per_mass
dtypes: float64(241), int64(1), object(93)
memory usage: 3.3+ MB

In [126]:
df.head()

,Unnamed: 0,meta_DOI_URL,meta_authors,meta_year,meta_title,meta_journal,site_country,site_country_iso2,site_region_local,site_climate_zone,...,GHG_C12_total,GHG_C34_total,GHG_em_sum_total,GHG_P1_total,GHG_P2_total,GHG_P34_total,GHG_P4_total,GHG_P56_total,GHG_P78_total,GHG_per_mass
0,0,No data,No data,No data,No data,No data,Austria,AT,No data,No data,...,NaN,NaN,101921.4321,NaN,NaN,NaN,NaN,NaN,NaN,0.003705
1,1,No data,"Alexander Passer, Helmuth Kreiner",No data,AT6 - Karmeliterhof,A57 case study report,Austria,AT,Graz,(D) Continental,...,NaN,NaN,16251.6600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,No data,No data,No data,No data,No data,Austria,AT,No data,No data,...,NaN,NaN,76937.8800,NaN,NaN,NaN,NaN,NaN,NaN,0.004256
3,3,No data,No data,No data,No data,No data,Austria,AT,No data,No data,...,NaN,NaN,7760.9200,NaN,NaN,NaN,NaN,NaN,NaN,0.003755
4,4,No data,No data,No data,No data,No data,Austria,AT,No data,No data,...,NaN,NaN,73264.3500,NaN,NaN,NaN,NaN,NaN,NaN,0.003629

In [127]:
df.describe()

,Unnamed: 0,bldg_year_complete,bldg_users_total,bldg_area_gfa,bldg_floors_ag,bldg_floors_bg,bldg_area_value,bldg_height,bldg_footprint,lca_RSP,...,GHG_C12_total,GHG_C34_total,GHG_em_sum_total,GHG_P1_total,GHG_P2_total,GHG_P34_total,GHG_P4_total,GHG_P56_total,GHG_P78_total,GHG_per_mass
count,1294.000000,330.000000,710.000000,1055.000000,830.000000,195.000000,423.000000,74.000000,62.000000,1268.000000,...,275.000000,205.000000,1.005000e+03,650.000000,670.000000,670.000000,666.000000,645.000000,551.000000,272.000000
mean,646.500000,2008.112121,60.261549,4797.306550,4.031325,1.271795,6016.184161,26.789189,851.623548,53.518927,...,2321.905441,1538.185831,4.595358e+04,2237.119107,3560.500249,2383.537179,3070.739160,3600.862111,356.757936,0.007243
std,373.689934,14.733587,234.654388,15852.959380,5.440897,0.636497,20307.786749,32.056306,2492.269024,12.087505,...,8259.834536,3675.030928,1.886603e+05,10354.741164,11536.426059,8123.095542,12753.048343,13406.241290,931.348331,0.010428
min,0.000000,1940.000000,1.670000,21.000000,1.000000,1.000000,21.000000,2.400000,21.000000,14.000000,...,-16360.000000,-19284.000000,8.000000e+01,14.401800,24.229333,50.030600,1.201600,15.594461,0.932000,0.000583
25%,323.250000,2005.000000,2.000000,138.699997,2.000000,1.000000,151.200000,3.000000,70.575000,50.000000,...,47.972542,53.138843,1.361207e+03,77.020925,259.127800,142.447500,302.921650,366.735600,59.885000,0.003686
50%,646.500000,2012.000000,4.000000,269.610000,2.000000,1.000000,586.000000,8.100000,192.000000,50.000000,...,205.002000,377.200000,2.839800e+03,129.829200,427.050867,321.019100,480.336500,526.161600,85.260000,0.005114
75%,969.750000,2019.000000,23.000000,2671.000000,4.000000,1.000000,3537.000000,49.200000,679.425000,50.000000,...,1763.000000,1301.308768,2.213640e+04,764.340463,1998.143250,1147.404500,1822.247600,1978.160000,367.887100,0.007044
max,1293.000000,2025.000000,2991.000000,216000.000000,40.000000,5.000000,216000.000000,110.200000,19433.000000,100.000000,...,104465.000000,25747.470000,2.667087e+06,114628.700000,150898.350000,101784.000000,182903.837398,140951.237343,16320.000000,0.147943

# Benchmarking // Whole Life Carbon

In [128]:
import pandas as pd

# List of variables to compute statistics for
variables = [
    'GHG_A123_m2a_harm', 
    'GHG_A45_m2a_harm',
    'GHG_B1234_m2a_harm',
    'GHG_B67_m2a_harm',
    'GHG_C12_m2a_harm',
    'GHG_C34_m2a_harm',]

# Filter the dataset
filtered_df = df[(df['site_region_geoscheme'] == 'Western Europe') 
                 & (df['bldg_use_subtype'] == 'Single family house')
                 #& (df['bldg_energy_class_general'] == 'New Standard') 
                 #& (df['bldg_struct_type'] == 'massive brick')
                 ]

# Initialize an empty DataFrame to store the results
results_df = pd.DataFrame()

# Loop through each variable to compute the descriptive statistics
for var in variables:
    descriptive_stats = filtered_df[var].describe(percentiles=[.25, .5, .75])
    percentiles = descriptive_stats[['count', '25%', '50%', '75%']]
    percentiles_df = percentiles.to_frame().T
    results_df = pd.concat([results_df, percentiles_df])

results_df

                    count       25%       50%        75%
GHG_A123_m2a_harm    24.0  5.467654  6.228475   6.644924
GHG_A45_m2a_harm     23.0  0.380667  0.752923   0.794030
GHG_B1234_m2a_harm   23.0  3.012792  3.946062   4.403784
GHG_B67_m2a_harm    191.0  1.374600  4.292308  10.401850
GHG_C12_m2a_harm     24.0  0.203112  0.226940   0.240334
GHG_C34_m2a_harm     18.0  0.197095  0.204283   0.240584

In [129]:
import pandas as pd

# List of variables to compute statistics for
variables = [
    'GHG_A123_m2a_harm', 
    'GHG_A45_m2a_harm',
    'GHG_B1234_m2a_harm',
    'GHG_B67_m2a_harm',
    'GHG_C12_m2a_harm',
    'GHG_C34_m2a_harm',]

# Filter the dataset
filtered_df = df[(df['site_region_geoscheme'] == 'Western Europe') 
                 & (df['bldg_use_subtype'] == 'Single family house')
                 #& (df['bldg_energy_class_general'] == 'New Advanced') 
                 & (df['bldg_struct_type'] == 'frame wood')
                 ]

# Initialize an empty DataFrame to store the results
results_df = pd.DataFrame()

# Loop through each variable to compute the descriptive statistics
for var in variables:
    descriptive_stats = filtered_df[var].describe(percentiles=[.25, .5, .75])
    percentiles = descriptive_stats[['count', '25%', '50%', '75%']]
    percentiles_df = percentiles.to_frame().T
    results_df = pd.concat([results_df, percentiles_df])

results_df

                    count       25%       50%        75%
GHG_A123_m2a_harm     6.0  4.031171  4.102981   4.265320
GHG_A45_m2a_harm      6.0  0.380667  0.389260   0.404856
GHG_B1234_m2a_harm    6.0  3.099536  3.121530   3.187904
GHG_B67_m2a_harm     23.0  1.135000  1.379100  19.051566
GHG_C12_m2a_harm      6.0  0.137066  0.141438   0.147865
GHG_C34_m2a_harm      6.0  0.198964  0.204283   0.210111

In [130]:
filtered_df['bldg_struct_type'].value_counts()

frame wood    26
Name: bldg_struct_type, dtype: int64

In [131]:
import pandas as pd

# List of variables to compute statistics for
variables = [
    'GHG_A123_m2a_harm', 
    'GHG_A45_m2a_harm',
    'GHG_B1234_m2a_harm',
    'GHG_B67_m2a_harm',
    'GHG_C12_m2a_harm',
    'GHG_C34_m2a_harm',]

# Filter the dataset
filtered_df = df[(df['site_region_geoscheme'] == 'Eastern Asia') 
                 & (df['bldg_use_subtype'] == 'Multi-family house')
                 #& (df['bldg_energy_class_general'] == 'New Standard') 
                 #& (df['bldg_struct_type'] == 'frame wood')
                 ]

# Initialize an empty DataFrame to store the results
results_df = pd.DataFrame()

# Loop through each variable to compute the descriptive statistics
for var in variables:
    descriptive_stats = filtered_df[var].describe(percentiles=[.25, .5, .75])
    percentiles = descriptive_stats[['count', '25%', '50%', '75%']]
    percentiles_df = percentiles.to_frame().T
    results_df = pd.concat([results_df, percentiles_df])

results_df

                    count        25%        50%     75%
GHG_A123_m2a_harm    45.0   6.180000   8.250000   8.530
GHG_A45_m2a_harm     36.0   0.585000   0.905000   1.330
GHG_B1234_m2a_harm   21.0   0.666667   1.680000   1.710
GHG_B67_m2a_harm     43.0  19.350000  34.407143  52.335
GHG_C12_m2a_harm     33.0   0.190000   0.380000   0.480
GHG_C34_m2a_harm      4.0   0.710000   1.070000   1.430

In [132]:
import pandas as pd

# List of variables to compute statistics for
variables = [
    'GHG_A123_m2a_harm', 
    'GHG_A45_m2a_harm',
    'GHG_B1234_m2a_harm',
    'GHG_B67_m2a_harm',
    'GHG_C12_m2a_harm',
    'GHG_C34_m2a_harm',]

# Filter the dataset
filtered_df = df[(df['site_region_geoscheme'] == 'Australia and New Zealand') 
                 #& (df['bldg_use_subtype'] == 'Office')
                 #& (df['bldg_energy_class_general'] == 'New Standard') 
                 #& (df['bldg_struct_type'] == 'massive brick')
                 ]

# Initialize an empty DataFrame to store the results
results_df = pd.DataFrame()

# Loop through each variable to compute the descriptive statistics
for var in variables:
    descriptive_stats = filtered_df[var].describe(percentiles=[.25, .5, .75])
    percentiles = descriptive_stats[['count', '25%', '50%', '75%']]
    percentiles_df = percentiles.to_frame().T
    results_df = pd.concat([results_df, percentiles_df])

print(results_df)

                    count   25%     50%        75%
GHG_A123_m2a_harm    38.0  3.06   3.635   4.375000
GHG_A45_m2a_harm     29.0  0.29   0.410   0.410000
GHG_B1234_m2a_harm   11.0  1.03   1.190   4.876923
GHG_B67_m2a_harm     48.0  7.48  29.925  32.665000
GHG_C12_m2a_harm      0.0   NaN     NaN        NaN
GHG_C34_m2a_harm      0.0   NaN     NaN        NaN

# Benchmarking // Material Intensity

In [133]:
import pandas as pd

# List of variables to compute statistics for
variables = [
    'mi_fr_concrete', 
    'mi_fr_steel',
    'mi_fr_wood',
    'mi_fr_brick',
    'mi_fr_glass',
    'mi_fr_plastics',
    'mi_fr_aluminum',
    'mi_fr_copper',
    ]
    

# Filter the dataset
filtered_df = df[
    #(df['site_region_geoscheme'] == 'Australia and New Zealand') 
    #& (df['bldg_use_subtype'] == 'Office')
    #& (df['bldg_energy_class_general'] == 'New Standard')
    #&
    (df['bldg_struct_type'] == 'massive concrete')
    ]

# Initialize an empty DataFrame to store the results
results_df = pd.DataFrame()

# Loop through each variable to compute the descriptive statistics
for var in variables:
    descriptive_stats = filtered_df[var].describe(percentiles=[.25, .5, .75])
    percentiles = descriptive_stats[['count', '25%', '50%', '75%']]
    percentiles_df = percentiles.to_frame().T
    results_df = pd.concat([results_df, percentiles_df])

print(results_df)

                count         25%         50%          75%
mi_fr_concrete   28.0  849.378004  849.378004  1097.013946
mi_fr_steel      25.0   17.039864   17.039864    50.984624
mi_fr_wood       16.0    6.734521    6.734521     6.734521
mi_fr_brick       6.0   58.331922   81.368591    90.318877
mi_fr_glass      15.0   12.476675   12.476675    12.476675
mi_fr_plastics    0.0         NaN         NaN          NaN
mi_fr_aluminum    0.0         NaN         NaN          NaN
mi_fr_copper      0.0         NaN         NaN          NaN

In [134]:
print('Finished: ' + script_title)

Finished: GBDB CarbEnMats // Benchmarking